version: "3"

services:
  db:
    image: mariadb:10.5.8
    container_name: "${PROJECT}-db"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "drupal"
      MYSQL_DATABASE: "drupal"
      MYSQL_USER: "drupal"
      MYSQL_PASSWORD: "drupal"
    restart: unless-stopped
    env_file: .env
    networks:
      - internal
    labels:
      - traefik.enable=false

  varnish:
    image: varnish:stable
    container_name: varnishcache
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G  
    command: "-p default_keep=300 -p http_max_hdr=512 -p http_resp_hdr_len=1024768 -p http_resp_size=3024768 -p thread_pool_min=200 -p thread_pool_max=500 -p http_req_size=64000"
#    command: "-p default_keep=300"
    depends_on:
      - web

  php:
    build:
      context: .
      dockerfile: ./.deploy/php/Dockerfile
    container_name: "${PROJECT}-php"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - '9000:80'
    networks:
      - internal
      - database
    labels:
      - traefik.enable=false
    deploy:
      resources:
        limits:
          memory: 512M
  web:
    image: webdevops/apache:latest
    container_name: ${PROJECT}-web
    volumes:
      - ./:/var/www/html:ro
      - ./.deploy/apache/main.conf:/opt/docker/etc/httpd/main.conf
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/web
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - internal
      - web
      - database
    links:
      - php

    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}.rule=HostRegexp(`${PROJECT_DOMAIN}`, `www.${PROJECT_DOMAIN}` , `{subdomain:[a-zA-Z0-9-]+}${PROJECT_DOMAIN}`)
      - traefik.http.routers.${PROJECT}.tls=true
      - traefik.http.routers.${PROJECT}.tls.certresolver=le-cloudflare
  redis:
    image: redis:6
    networks:
      - internal

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  db-data:
