version: "3"

services:
  db:
    image: mysql:8.0.34
    container_name: "${PROJECT}-db"
    volumes:
      - db-data-mysql:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    networks:
      - internal
    labels:
      - traefik.enable=false

  php:
    build:
      context: .
      dockerfile: ./.deploy/php/Dockerfile
    container_name: "${PROJECT}-php"
    volumes:
      - ./:/var/www/html
    ports:
      - '9000:80'
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    networks:
      - internal
    labels:
      - traefik.enable=false

  web:
    image: webdevops/apache:latest
    container_name: ${PROJECT}-web
    volumes:
      - ./:/var/www/html:ro
      - ./.deploy/apache/main.conf:/opt/docker/etc/httpd/main.conf
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/web
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - internal
      - web
    links:
      - php
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}.rule=HostRegexp(`${PROJECT_DOMAIN}`, `www.${PROJECT_DOMAIN}` , `{subdomain:[a-zA-Z0-9-]+}${PROJECT_DOMAIN}`)
      - traefik.http.routers.${PROJECT}.tls=true
      - traefik.http.routers.${PROJECT}.tls.certresolver=le-cloudflare

  redis:
    image: redis:6
    networks:
      - internal
    labels:
      - traefik.enable=false
    restart: unless-stopped
    
networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  db-data-mysql:
