version: "3"

services:
  db:
    image: mariadb:10.5.8
    container_name: "${PROJECT}-db"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    networks:
      - internal
    labels:
      - traefik.enable=false
    deploy:
      resources:
        limits:
          memory: 512M

  php:
    build:
      context: .
      dockerfile: ./.deploy/php/Dockerfile
    container_name: "${PROJECT}-php"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - '9000:80'
    networks:
      - internal
    labels:
      - traefik.enable=false

  web:
    image: nginx
    container_name: ${PROJECT}-web
    volumes:
      - ./:/var/www/html:ro
      - ./.deploy/nginx/conf:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    networks:
      - internal
      - web
    labels:
      - traefik.enable=false
  redis:
    image: redis:6
    networks:
      - internal

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  db-data:
