default:
  autoload:
    '': /opt/atlassian/pipelines/agent/build/tests/features/bootstrap
  suites:
    default:
      contexts:
        - ComplexFormElementsContext
        - GinUiContext
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - DrevOps\BehatScreenshotExtension\Context\ScreenshotContext
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    DrevOps\BehatScreenshotExtension:
      dir: /opt/atlassian/pipelines/agent/build/screenshots
      fail: true
      purge: false
    Drupal\MinkExtension:
      files_path: '/opt/atlassian/pipelines/agent/build/tests'
      selenium2: ~
      browser_name: chrome
      default_session: command_line_browser
      javascript_session: chromium
      sessions:
        command_line_browser:
          browserkit_http: ~
        chromium:
          chrome:
            api_url: http://localhost:9222
            validate_certificate: false
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        alias: 'self.ci-behat'
        binary: '../vendor/bin/drush'
      drupal:
        drupal_root: '/opt/atlassian/pipelines/agent/build/web'
      region_map:
        footer: "footer"
        navbar: ".navbar"
        content: ".region-content"
        breadcrumb: ".block-system-breadcrumb-block"
        media_library: ".media-library-widget-modal .ui-dialog-buttonpane .ui-dialog-buttonset"
        drupal_modal: "#drupal-modal"
        modal_dialog: ".ui-dialog"
        modal_dialog_buttons: ".ui-dialog .ui-dialog-buttonpane"
        gutenberg_post_header: ".edit-post-header"
      selectors:
        message_selector: '.notification,.messages-list'
        error_message_selector: '.notification.is-danger,.messages-list__item.messages--error'
        success_message_selector: '.notification.is-success,.messages-list__item.messages--status'
