_core:
  default_config_hash: ceCx5XZ_ay1Mxcv-sB95U_fBKoVkpvo8RaQiwutSZLI
content: "# Allow search.gov access\r\nUser-agent: usasearch\r\nAllow: /\r\n\r\n# Do not allow robot access\r\nUser-agent: *\r\nDisallow: /\r\n\r\nSitemap: https://uscourts-dev.agileana.com/sitemap.xml\r\n"
