_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
minimum_single: 20
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 720
max_shown_results: null
use_relative_width: false
jquery_selector: 'select:visible'
search_contains: false
disable_search: false
allow_single_deselect: false
disabled_themes:
  claro: '0'
  olivero: '0'
  gin: '0'
  uscgov: '0'
chosen_include: 0
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
