_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  admin_toolbar: 0
  akamai: 0
  ape: 0
  auto_entitylabel: 0
  autologout: 0
  automated_cron: 0
  bean_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor5: 0
  config: 0
  config_pages: 0
  config_split: 0
  contextual: 0
  ctools: 0
  customerror: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  faqfield: 0
  feeds: 0
  feeds_log: 0
  field: 0
  field_group: 0
  field_group_migrate: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  fpa: 0
  google_tag: 0
  gutenberg: 0
  gutenberg_uswds: 0
  gutenberg_uswds_accordion: 0
  gutenberg_uswds_card: 0
  gutenberg_uswds_modal: 0
  gutenberg_uswds_process_list: 0
  gutenberg_uswds_summary_box: 0
  help: 0
  history: 0
  honeypot: 0
  html_processors: 0
  htmlpurifier: 0
  image: 0
  image_effects: 0
  image_link_formatter: 0
  inline_entity_form: 0
  job_scheduler: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  libraries: 0
  link: 0
  linkit: 0
  maxlength: 0
  media: 0
  media_library: 0
  media_migration: 0
  media_migration_tools: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_position: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migmag: 0
  migmag_process: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  module_filter: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pathologic: 0
  phpass: 0
  piksel: 0
  redirect: 0
  redis: 0
  remote_stream_wrapper: 0
  responsive_image: 0
  robotstxt: 0
  scheduler: 0
  sdc: 0
  search: 0
  seckit: 0
  serialization: 0
  sharethis: 0
  shortcut: 0
  smart_sql_idmap: 0
  stage_file_proxy: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  transliterate_filenames: 0
  usc_migrate_adjustments: 0
  usc_migrate_boolean: 0
  usc_migrate_gutenberg: 0
  usc_migrate_list: 0
  user: 0
  usfedgov_google_analytics: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  extlink: 1
  pathauto: 1
  xmlsitemap: 1
  password_policy: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  claro: 0
  uscgov: 0
  uscadmin: 0
profile: minimal
