_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: -46
    expanded: false
    enabled: false
  config_pages__global_site_settings:
    menu_name: admin
    parent: system.themes_page
    weight: 0
    expanded: false
    enabled: true
