_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: d7bed51a-e7b2-48f3-ab88-fcb0d7c6be91
name: 'United States Courts'
mail: AOWebmaster@ao.uscourts.gov
slogan: ''
page:
  403: /customerror/403
  404: /customerror/404
  front: /node/3543
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
