_core:
  default_config_hash: LqXuXXQCTd1NWw7dGLef0PCi3_aEEWQuogAblo4hHaE
hotlink: true
origin: 'https://uscourts-dev.agileana.com'
origin_dir: sites/default/files
proxy_headers: ''
use_imagecache_root: true
verify: false
excluded_extensions: ''
